# Generated by Django 5.0.3 on 2024-04-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherhome', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='permission',
        ),
    ]
